- name: Deploy to production
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.PRODUCTION_HOST }}
    username: ${{ secrets.PRODUCTION_USER }}
    key: ${{ secrets.SSH_KEY }}
    script: |
      docker-compose -f docker-compose.prod.yml up -d --build 